version: '3.8'
services:
  queery:
    image: queery:latest
    env_file: .env
    command: ["queery"]
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
       - db-data:/var/lib/postgresql/data
volumes:
  db-data:
