version: '3.8'
services:
  queery:
    container_name: "queery"
    image: queery:latest
    env_file: .env
    command: ["queery"]
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: unless-stopped
  db:
    container_name: "queery-db"
    image: postgres:16
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
       - db-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  db-data:
